apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml

images:
- name: cafe-fep
  newName: 172.30.1.68:5000/cafe-fep
  newTag: dev   # 이미지 태그는 환경에 따라 달라질 수 있습니다.
