apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: cafe-fep
  newName: 172.30.1.68:5000/cafe_fep-django # 내 레지스트리 주소와 이미지 이름
  newTag: 0.18.2-dev-3   # 이미지 태그는 환경에 따라 달라질 수 있습니다.
